var namespace_z_k_web_1_1_plugins_1_1_shopping_1_1_logistics_1_1src_1_1_form_field_handlers =
[
    [ "LogisticsPriceRulesEditor", "dc/d80/class_z_k_web_1_1_plugins_1_1_shopping_1_1_logistics_1_1src_1_1_form_field_handlers_1_1_logistics_price_rules_editor.html", "dc/d80/class_z_k_web_1_1_plugins_1_1_shopping_1_1_logistics_1_1src_1_1_form_field_handlers_1_1_logistics_price_rules_editor" ]
];