var namespace_z_k_web_1_1_plugins_1_1_common_1_1_admin_settings_1_1src_1_1_generic_forms_for_admin_settings =
[
    [ "LocaleSettingsForm", "d8/d91/class_z_k_web_1_1_plugins_1_1_common_1_1_admin_settings_1_1src_1_1_generic_forms_for_admin_settings_1_1_locale_settings_form.html", "d8/d91/class_z_k_web_1_1_plugins_1_1_common_1_1_admin_settings_1_1src_1_1_generic_forms_for_admin_settings_1_1_locale_settings_form" ],
    [ "WebsiteSettingsForm", "dc/dd6/class_z_k_web_1_1_plugins_1_1_common_1_1_admin_settings_1_1src_1_1_generic_forms_for_admin_settings_1_1_website_settings_form.html", "dc/dd6/class_z_k_web_1_1_plugins_1_1_common_1_1_admin_settings_1_1src_1_1_generic_forms_for_admin_settings_1_1_website_settings_form" ]
];