var namespace_z_k_web_1_1_plugins_1_1_c_m_s_1_1_article_1_1src_1_1_generic_forms_for_admin_settings =
[
    [ "ArticleListSettingsForm", "d4/d16/class_z_k_web_1_1_plugins_1_1_c_m_s_1_1_article_1_1src_1_1_generic_forms_for_admin_settings_1_1_article_list_settings_form.html", "d4/d16/class_z_k_web_1_1_plugins_1_1_c_m_s_1_1_article_1_1src_1_1_generic_forms_for_admin_settings_1_1_article_list_settings_form" ]
];