var namespace_z_k_web_1_1_plugins_1_1_common_1_1_region_1_1src_1_1_generic_forms_for_admin_settings =
[
    [ "RegionSettingsForm", "db/d42/class_z_k_web_1_1_plugins_1_1_common_1_1_region_1_1src_1_1_generic_forms_for_admin_settings_1_1_region_settings_form.html", "db/d42/class_z_k_web_1_1_plugins_1_1_common_1_1_region_1_1src_1_1_generic_forms_for_admin_settings_1_1_region_settings_form" ]
];