var namespace_z_k_web_1_1_plugins_1_1_common_1_1_language_switcher_1_1src_1_1_config =
[
    [ "LanguageSwitcherSettings", "dc/dd7/class_z_k_web_1_1_plugins_1_1_common_1_1_language_switcher_1_1src_1_1_config_1_1_language_switcher_settings.html", "dc/dd7/class_z_k_web_1_1_plugins_1_1_common_1_1_language_switcher_1_1src_1_1_config_1_1_language_switcher_settings" ]
];