var namespace_z_k_web_1_1_plugins_1_1_common_1_1_admin_1_1src_1_1_list_item_providers =
[
    [ "PrivilegesListItemGroupsProvider", "de/dec/class_z_k_web_1_1_plugins_1_1_common_1_1_admin_1_1src_1_1_list_item_providers_1_1_privileges_list_item_groups_provider.html", "de/dec/class_z_k_web_1_1_plugins_1_1_common_1_1_admin_1_1src_1_1_list_item_providers_1_1_privileges_list_item_groups_provider" ]
];