var namespace_z_k_web_1_1_plugins_1_1_common_1_1_admin_settings_1_1src_1_1_scaffolding =
[
    [ "AdminSettingsCrudPageBuilder", "d8/d09/class_z_k_web_1_1_plugins_1_1_common_1_1_admin_settings_1_1src_1_1_scaffolding_1_1_admin_settings_crud_page_builder.html", "d8/d09/class_z_k_web_1_1_plugins_1_1_common_1_1_admin_settings_1_1src_1_1_scaffolding_1_1_admin_settings_crud_page_builder" ],
    [ "AdminSettingsFormPageBuilder", "d8/dcf/class_z_k_web_1_1_plugins_1_1_common_1_1_admin_settings_1_1src_1_1_scaffolding_1_1_admin_settings_form_page_builder.html", "d8/dcf/class_z_k_web_1_1_plugins_1_1_common_1_1_admin_settings_1_1src_1_1_scaffolding_1_1_admin_settings_form_page_builder" ],
    [ "AdminSettingsSimplePageBuilder", "df/d35/class_z_k_web_1_1_plugins_1_1_common_1_1_admin_settings_1_1src_1_1_scaffolding_1_1_admin_settings_simple_page_builder.html", "df/d35/class_z_k_web_1_1_plugins_1_1_common_1_1_admin_settings_1_1src_1_1_scaffolding_1_1_admin_settings_simple_page_builder" ]
];