var namespace_z_k_web_1_1_plugins_1_1_shopping_1_1_logistics_1_1src_1_1_list_item_providers =
[
    [ "LogisticsTypeListItemProvider", "d2/d09/class_z_k_web_1_1_plugins_1_1_shopping_1_1_logistics_1_1src_1_1_list_item_providers_1_1_logistics_type_list_item_provider.html", "d2/d09/class_z_k_web_1_1_plugins_1_1_shopping_1_1_logistics_1_1src_1_1_list_item_providers_1_1_logistics_type_list_item_provider" ]
];