var namespace_z_k_web_1_1_plugins_1_1_common_1_1_user_panel_1_1src_1_1_scaffolding =
[
    [ "UserPanelCrudPageBuilder", "dc/d42/class_z_k_web_1_1_plugins_1_1_common_1_1_user_panel_1_1src_1_1_scaffolding_1_1_user_panel_crud_page_builder.html", "dc/d42/class_z_k_web_1_1_plugins_1_1_common_1_1_user_panel_1_1src_1_1_scaffolding_1_1_user_panel_crud_page_builder" ],
    [ "UserPanelFormPageBuilder", "de/dc2/class_z_k_web_1_1_plugins_1_1_common_1_1_user_panel_1_1src_1_1_scaffolding_1_1_user_panel_form_page_builder.html", "de/dc2/class_z_k_web_1_1_plugins_1_1_common_1_1_user_panel_1_1src_1_1_scaffolding_1_1_user_panel_form_page_builder" ],
    [ "UserPanelSimplePageBuilder", "d3/d7e/class_z_k_web_1_1_plugins_1_1_common_1_1_user_panel_1_1src_1_1_scaffolding_1_1_user_panel_simple_page_builder.html", "d3/d7e/class_z_k_web_1_1_plugins_1_1_common_1_1_user_panel_1_1src_1_1_scaffolding_1_1_user_panel_simple_page_builder" ]
];