var namespace_z_k_web_1_1_plugins_1_1_common_1_1_language_switcher_1_1src_1_1_admin_settings_pages =
[
    [ "LanguageSwitcherSettingsForm", "de/ddf/class_z_k_web_1_1_plugins_1_1_common_1_1_language_switcher_1_1src_1_1_admin_settings_pages_1_1_language_switcher_settings_form.html", "de/ddf/class_z_k_web_1_1_plugins_1_1_common_1_1_language_switcher_1_1src_1_1_admin_settings_pages_1_1_language_switcher_settings_form" ]
];